"""add token_version and token_prefix columns

Revision ID: a98e106b6154
Revises: 9d1b3811f9bc
Create Date: 2026-07-23 14:52:03.946763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98e106b6154'
down_revision: Union[str, None] = '9d1b3811f9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_prefix', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_token_token_prefix'), ['token_prefix'], unique=False)

    op.execute("UPDATE api_token SET token_prefix = 'legacy' WHERE token_prefix IS NULL")

    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.alter_column('token_prefix', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_token_prefix'))
        batch_op.drop_column('token_prefix')

    # ### end Alembic commands ###
