"""initial schema

Revision ID: 9d1b3811f9bc
Revises: 
Create Date: 2026-07-21 19:18:00.057254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9d1b3811f9bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('global_whitelist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extension_name', sa.String(length=255), nullable=False),
    sa.Column('postgres_versions', sqlite.JSON(), nullable=True),
    sa.Column('arch', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repository_source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sync_interval', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('auth_config', sqlite.JSON(), nullable=True),
    sa.Column('proxy_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('detail', sqlite.JSON(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('api_token_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['api_token_id'], ['api_token.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extension',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('publisher_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('channels', sqlite.JSON(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['repository_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_policy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('filters', sqlite.JSON(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('bandwidth_limit', sa.String(length=50), nullable=True),
    sa.Column('time_window', sqlite.JSON(), nullable=True),
    sa.Column('keep_old_versions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['repository_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extension_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extension_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('extra_mounts', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('downloaded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('diff_summary', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['sync_policy.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['repository_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extension_build',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('postgres_version', sa.String(length=50), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('flavor', sa.String(length=20), nullable=False),
    sa.Column('build', sa.String(length=50), nullable=True),
    sa.Column('package_path', sa.Text(), nullable=False),
    sa.Column('package_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['extension_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extension_build')
    op.drop_table('sync_task')
    op.drop_table('extension_version')
    op.drop_table('sync_policy')
    op.drop_table('extension')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('repository_source')
    op.drop_table('publisher')
    op.drop_table('global_whitelist')
    op.drop_table('api_token')
    # ### end Alembic commands ###
